language: c

sudo: false

env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - LUA=lua5.1
#    - LUA=lua5.2
#    - LUA=lua5.3
    - LUA=luajit     # latest stable version (2.0.4)
    - LUA=luajit2.0  # current head of 2.0 branch
    - LUA=luajit2.1  # current head of 2.1 branch

before_install:
  - source .travis/setenv_lua.sh
  - luarocks show busted || luarocks install busted
  - luarocks show luacov || luarocks install luacov
  - luarocks show luacov-coveralls || luarocks install luacov-coveralls
  - luarocks show luacheck || luarocks install luacheck

install:
  - luarocks make rockspecs/nginx-metrix-local-1.rockspec --local

script:
  - luacheck rockspecs/nginx-metrix-local-1.rockspec
  - busted

after_success:
  - luacov-coveralls -v

notifications:
  email:
    on_success: change
    on_failure: always