language: c

sudo: false

env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - LUA=lua5.1
#    - LUA=lua5.2
#    - LUA=lua5.3
    - LUA=luajit     # latest stable version (2.0.4)
    - LUA=luajit2.0  # current head of 2.0 branch
    - LUA=luajit2.1  # current head of 2.1 branch

before_install:
  - source .travis/setenv_lua.sh
  - luarocks install luacov-coveralls --server=https://luarocks.org/dev
  - luarocks install busted

install:
  - luarocks make rockspecs/nginx-metrix-local-1.rockspec

script:
  - busted

after_success:
  - luacov-coveralls -v

notifications:
  email:
    on_success: change
    on_failure: always